# Generated by Django 5.0.4 on 2024-05-06 20:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_alter_otp_time_alter_otp_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='time',
        ),
        migrations.AddField(
            model_name='otp',
            name='times',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 6, 20, 38, 4, 298469)),
        ),
    ]
